### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gsgoldma** [ZhUyU1997/open-pose-editor#1]
Failed to resolve import "i18next" from "src\i18n.ts". Does the file exist?
9:57:00 AM [vite] Internal server error: Failed to resolve import "i18next" from "src\i18n.ts". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/open-pose-editor/src/i18n.ts:1:20
  1  |  import i18next from "i18next";
     |                       ^
  2  |  import LanguageDetector from "i18next-browser-languagedetector";
  3  |  import commonEn from "./locales/en.json";
      at formatError (file:///D:/open-pose-editor/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41418:46)
      at TransformContext.error (file:///D:/open-pose-editor/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19)
      at normalizeUrl (file:///D:/open-pose-editor/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39706:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.transform (file:///D:/open-pose-editor/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39840:47)
      at async Object.transform (file:///D:/open-pose-editor/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///D:/open-pose-editor/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
Failed to resolve import "i18next" from "src\i18n.ts". Does the file exist?
Failed to resolve import "i18next" from "src\i18n.ts". Does the file exist? (x2)
Failed to resolve import "i18next" from "src\i18n.ts". Does the file exist? (x3)

**Comment by ZhUyU1997** [comment]
Did you execute "npm install" before running? It looks like the missing dependency of i18next
